### PR TITLE
doc: typo in example

### PR DESCRIPTION
**Pull request by bcho**

### CODE REVIEW

**Comment by peter-edge** [comment]
Run make contributors and push again

**Comment by bcho** [comment]
done!

**Comment by peter-edge** [comment]
Still failing Travis

**Comment by peter-edge** [comment]
Ah - `etc/config/example/prototool.yaml` is auto-generated from the template in `internal/x/cfginit` - you need to update the template there, and then run `make generate` instead of updating the `prototool.yaml` file directly.

**Comment by bcho** [comment]
ok, I will update it later :joy:

**Comment by bcho** [comment]
err, travis-ci is yelling but cannot fetch the log, can I rebuild?

**Comment by peter-edge** [comment]
```
make generate produced a diff, make sure to check these in:
0a1
>  M CONTRIBUTORS
make: *** [checknodiffgenerated] Error 1
```

Did you manually add to CONTRIBUTORS? It's an automatic thing, from `make contributors`. Reset the file and run `make contributors`.

**Comment by bcho** [comment]
@peter-edge done

**Pull request merged**
