### PR TITLE
Fix proto2 format bug, unintended rewrite from repeated to optional

### PR DESCRIPTION
**Pull request by odsod**
Hello and happy new year from Sweden!

Please let me know if you'd like me to add more tests or make any other changes to this bugfix.

Feel free to append/rewrite commits as you see fit!

Cheers

### CODE REVIEW

**Comment by ohlsont** [comment]
What an amazing PR, would be nice to see a release with this. @peter-edge a review maybe? :rainbow:

**Comment by peter-edge** [comment]
Quick pro tip: it's all good, but as a general courtesy, don't tag individual maintainers on GitHub for reviews for company repositories - we have our own review process - all good though!

LGTM. Note we're in a bit of flux so we won't have an actual release for a while, our apologies, but there's instructions in the README.md on how to install using Golang 1.11+ from a specific branch/commit. Use https://github.com/myitcv/gobin

```
# Install to /path/to/bin
GOBIN=/path/to/bin gobin github.com/uber/prototool/cmd/prototool@COMMIT
```

**Comment by peter-edge** [comment]
A note: pin to a commit, dev is unstable (although not very)

**Comment by odsod** [comment]
Thank you Peter! Apologies for the mention, and thanks for the heads up on release lead time. Thanks for recommending gobin - that'll do the trick.

**Comment by peter-edge** [comment]
No worries! Happy New Year!

**Pull request merged**
