### PR TITLE
Add protoc-gen-mypy to Docker image

### PR DESCRIPTION
**Pull request by juzna**
The mypy compiler (https://github.com/dropbox/mypy-protobuf/) generates typing information, which is very useful for IDEs and static analysis.

Also upgrading to newest versions of dependencies in Alpine in separate commit, because pinned versions are not available anymore, so the image can't be built currently.

### CODE REVIEW

**Comment by smaye81** [comment]
Thank for being patient on this.  If you are still interested in this PR, can you rebase dev and update any outdated deps in the Dockerfile?  If not, I can just close the PR.

**Comment by smaye81** [comment]
Closing.  If this is still needed, let's discuss.  We'd prefer just building your own image off of `uber/prototool` anyway.

**Comment by juzna** [comment]
Yes, we ended up using our own protool image. I just thought that mypy is so generic that it would be useful to many.

**Comment by smaye81** [comment]
Nice, I'm glad you were able to work it out.  Thanks for putting up the original PR, though.  Glad you found a solution.

**Pull request closed without merging**
